//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revision
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int St_ID { get; set; }
        public string St_Name { get; set; }
        public Nullable<int> Cid { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
